import {integer, pgEnum, pgTable, serial ,text ,timestamp, varchar} from 'drizzle-orm/pg-core'

export const userSystemnEnum = pgEnum('user_system_enum',['system','user']); // -> this is the enum we have created to identify that waether message is generated by user or system
export const chats = pgTable('chats',{
    id: serial('id').primaryKey(),
    pdfName : text('pdfName').notNull(),
    pdfUrl : text('pdfUrl').notNull(),
    createdAt : timestamp('createdAt').notNull().defaultNow(),
    userId : varchar('userId', {length :256}).notNull(), // pointing to the clerk user id
    fileKey : text('fileKey').notNull(), // retrerive the file from s3
})

export const messages = pgTable('messages',{
    id: serial('id').primaryKey(),
    chatId : integer('chat_id').references(()=>chats.id).notNull(), // this is the foreign key -> setup the many to one relationship
    contenbt : text('content').notNull(),
    createdAt : timestamp('createdAt').notNull().defaultNow(),
    role : userSystemnEnum('role').notNull(),
})



// DRIZLLE ORM -> this is the ORM we are using to create the tables in the database OR INTERACT WITH DATABSE 
///DRIZZKE KIT -> tis is provide the utility function to create migrations and all other schema is synced up with database